version: '3'
services:
  my-node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8069:8069"
    volumes:
      - ./:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: adil
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
  