# Use the official Node.js 18.16.1 base image
FROM node:18.16.1

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code to the container
COPY . .

# Expose port 8069
EXPOSE 8069

# Start the application using nodemon
CMD ["npm", "run", "dev"]

 